// <auto-generated />
using System;
using GamesResults;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamesResults.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251218093321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActionsRoles", b =>
                {
                    b.Property<int>("ActionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("ActionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ActionsRoles", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsChange")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLogDetails")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("ObjectTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ObjectTypeId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("ObjectTypeId", "Name");

                    b.ToTable("Actions", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.PlayerRankingView", b =>
                {
                    b.Property<double>("AveragePlace")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastTournamentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("RatingCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TournamentCount")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView("vw_PlayerRankings", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionId")
                        .HasColumnType("integer");

                    b.Property<int>("LogLevel")
                        .HasColumnType("integer");

                    b.Property<string>("LogText")
                        .HasColumnType("text");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ObjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<long?>("UserId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("ObjectId");

                    b.HasIndex("UserId1");

                    b.ToTable("Logs", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.LogDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LogId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.ToTable("LogDetails", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Object", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("DeleterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<long?>("EditorId")
                        .HasColumnType("bigint");

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SortIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DeleterId");

                    b.HasIndex("EditorId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TypeId");

                    b.ToTable("Objects", "Bowling");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GamesResults.Models.ObjectProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataFormat")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DictionaryTypeName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayExpr")
                        .HasColumnType("text");

                    b.Property<string>("GroupTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsArray")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBoolean")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGuid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHiddenByDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHiddenInLogDetail")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIdentifier")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInclude")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMultiline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNotAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNumeric")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsObject")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsString")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NameSpace")
                        .HasColumnType("text");

                    b.Property<int?>("ObjectTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedField")
                        .HasColumnType("text");

                    b.Property<string>("RelatedType")
                        .HasColumnType("text");

                    b.Property<int?>("SortIndex")
                        .HasColumnType("integer");

                    b.Property<string>("SubGroupTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TypeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ObjectTypeId", "Name")
                        .IsUnique();

                    b.HasIndex("ObjectTypeId", "Title", "GroupTitle", "SubGroupTitle")
                        .IsUnique();

                    b.ToTable("ObjectProperties", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayExpr")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NameSpace")
                        .HasColumnType("text");

                    b.Property<long?>("RootContainerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RootContainerId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("ObjectTypes", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDepartment")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPosition")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Roles", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birthday");

                    b.Property<int?>("CanBeGip")
                        .HasColumnType("integer")
                        .HasColumnName("can_be_gip");

                    b.Property<string>("DataSource")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("data_source")
                        .HasDefaultValueSql("'B'::character varying");

                    b.Property<DateTime>("DtChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dt_change")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DtFinish")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dt_finish");

                    b.Property<DateTime?>("DtStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dt_start");

                    b.Property<string>("EMail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("e_mail");

                    b.Property<string>("EmpNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("emp_number");

                    b.Property<string>("ExternalKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_key");

                    b.Property<int?>("Greid")
                        .HasColumnType("integer")
                        .HasColumnName("greid");

                    b.Property<string>("Host")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("host");

                    b.Property<long?>("IdExternal")
                        .HasColumnType("bigint")
                        .HasColumnName("id_external");

                    b.Property<long?>("IdFuncOtdel")
                        .HasColumnType("bigint")
                        .HasColumnName("id_func_otdel");

                    b.Property<long?>("IdFuncSubdivision")
                        .HasColumnType("bigint")
                        .HasColumnName("id_func_subdivision");

                    b.Property<int?>("IdInt")
                        .HasColumnType("integer")
                        .HasColumnName("id_int");

                    b.Property<long?>("IdOrganization")
                        .HasColumnType("bigint")
                        .HasColumnName("id_organization");

                    b.Property<long?>("IdOtdel")
                        .HasColumnType("bigint")
                        .HasColumnName("id_otdel");

                    b.Property<long?>("IdPosition")
                        .HasColumnType("bigint")
                        .HasColumnName("id_position");

                    b.Property<long?>("IdRoom")
                        .HasColumnType("bigint")
                        .HasColumnName("id_room");

                    b.Property<long?>("IdSubdivision")
                        .HasColumnType("bigint")
                        .HasColumnName("id_subdivision");

                    b.Property<int>("IdType")
                        .HasColumnType("integer")
                        .HasColumnName("id_type");

                    b.Property<string>("Inn")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("inn");

                    b.Property<string>("IpAdress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsChief")
                        .HasColumnType("boolean")
                        .HasColumnName("is_chief");

                    b.Property<string>("Login")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("phone");

                    b.Property<string>("Placement")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("placement");

                    b.Property<long?>("PmObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("pm_ObjectId");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remark");

                    b.Property<Guid>("SapsanId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("short_name");

                    b.Property<byte[]>("Sid")
                        .HasColumnType("bytea")
                        .HasColumnName("sid");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasDefaultValueSql("10");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Users", "Bowling");
                });

            modelBuilder.Entity("ObjectPropertiesEditRoles", b =>
                {
                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("PropertyId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ObjectPropertiesEditRoles", "Bowling");
                });

            modelBuilder.Entity("UsersRoles", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersRoles", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.PlayerRating", b =>
                {
                    b.HasBaseType("GamesResults.Models.Object");

                    b.Property<double>("AveragePlace")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double>("AverageScore")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PeakRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1500);

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1500);

                    b.Property<long>("RatingHistoryId")
                        .HasColumnType("bigint");

                    b.Property<double>("Top10Percentage")
                        .HasColumnType("double precision");

                    b.Property<double>("Top3Percentage")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalGames")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPins")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentCount")
                        .HasColumnType("integer");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlayerRatings_PlayerId");

                    b.HasIndex("Rating")
                        .HasDatabaseName("IX_PlayerRatings_Rating");

                    b.ToTable("PlayerRatings", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.RatingHistory", b =>
                {
                    b.HasBaseType("GamesResults.Models.Object");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NewRating")
                        .HasColumnType("integer");

                    b.Property<int>("OldRating")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerRatingId")
                        .HasColumnType("bigint");

                    b.Property<int>("RatingChange")
                        .HasColumnType("integer");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("IX_RatingHistories_TournamentId");

                    b.HasIndex("PlayerRatingId", "ChangeDate")
                        .HasDatabaseName("IX_RatingHistories_Player_Date");

                    b.ToTable("RatingHistories", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Team", b =>
                {
                    b.HasBaseType("GamesResults.Models.Object");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GenderTeam")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SportType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Teams_Name");

                    b.ToTable("Teams", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.TeamMember", b =>
                {
                    b.HasBaseType("GamesResults.Models.Object");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_TeamMembers_PlayerId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_TeamMembers_TeamId");

                    b.ToTable("TeamMembers", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Tournament", b =>
                {
                    b.HasBaseType("GamesResults.Models.Object");

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OilId")
                        .HasColumnType("bigint");

                    b.Property<bool>("RatingsUpdated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RatingsUpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("TournamentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Unknown");

                    b.HasIndex("CityId");

                    b.HasIndex("OilId");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_Tournaments_StartDate");

                    b.ToTable("Tournaments", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.TournamentDocument", b =>
                {
                    b.HasBaseType("GamesResults.Models.Object");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Md5Hash")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("StoredFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("IX_TournamentDocuments_TournamentId");

                    b.ToTable("TournamentDocuments", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.TournamentResult", b =>
                {
                    b.HasBaseType("GamesResults.Models.Object");

                    b.Property<long?>("BowlingId")
                        .HasColumnType("bigint");

                    b.Property<int>("Game1")
                        .HasColumnType("integer");

                    b.Property<int>("Game2")
                        .HasColumnType("integer");

                    b.Property<int>("Game3")
                        .HasColumnType("integer");

                    b.Property<int>("Game4")
                        .HasColumnType("integer");

                    b.Property<int>("Game5")
                        .HasColumnType("integer");

                    b.Property<int>("Game6")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTeam")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("OriginalAverage")
                        .HasColumnType("double precision");

                    b.Property<int?>("OriginalTotal")
                        .HasColumnType("integer");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Summ")
                        .HasColumnType("integer");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasIndex("BowlingId");

                    b.HasIndex("Place")
                        .HasDatabaseName("IX_TournamentResults_Place");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_TournamentResults_PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("IX_TournamentResults_TournamentId");

                    b.HasIndex("TournamentId", "Place")
                        .HasDatabaseName("IX_TournamentResults_Tournament_Place");

                    b.ToTable("Results", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Container", b =>
                {
                    b.HasBaseType("GamesResults.Models.Object");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Containers", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.DictionaryItem", b =>
                {
                    b.HasBaseType("GamesResults.Models.Object");

                    b.Property<long?>("DictionaryTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsNotUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("name");

                    b.HasIndex("DictionaryTypeId");

                    b.ToTable("DictionaryItems", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Component", b =>
                {
                    b.HasBaseType("GamesResults.Models.Container");

                    b.Property<int?>("LoadActionId")
                        .HasColumnType("integer");

                    b.HasIndex("LoadActionId");

                    b.ToTable("Components", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.DictionaryType", b =>
                {
                    b.HasBaseType("GamesResults.Models.Container");

                    b.ToTable("DictionaryTypes", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.System", b =>
                {
                    b.HasBaseType("GamesResults.Models.Container");

                    b.Property<bool?>("IsBlocked")
                        .HasColumnType("boolean");

                    b.ToTable("System", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Bowling", b =>
                {
                    b.HasBaseType("GamesResults.Models.DictionaryItem");

                    b.ToTable("Bowlings", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.City", b =>
                {
                    b.HasBaseType("GamesResults.Models.DictionaryItem");

                    b.Property<long?>("DistrictId")
                        .HasColumnType("bigint");

                    b.HasIndex("DistrictId");

                    b.ToTable("Cities", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Discipline", b =>
                {
                    b.HasBaseType("GamesResults.Models.DictionaryItem");

                    b.ToTable("Disciplines", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.District", b =>
                {
                    b.HasBaseType("GamesResults.Models.DictionaryItem");

                    b.ToTable("Districts", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Oil", b =>
                {
                    b.HasBaseType("GamesResults.Models.DictionaryItem");

                    b.ToTable("Oils", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Player", b =>
                {
                    b.HasBaseType("GamesResults.Models.DictionaryItem");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Unknown");

                    b.Property<long>("PlayerRatingId")
                        .HasColumnType("bigint");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Players_Name");

                    b.ToTable("Players", "Bowling");
                });

            modelBuilder.Entity("GamesResults.Models.Page", b =>
                {
                    b.HasBaseType("GamesResults.Models.Component");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.ToTable("Pages", "Bowling");
                });

            modelBuilder.Entity("ActionsRoles", b =>
                {
                    b.HasOne("GamesResults.Models.Action", null)
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesResults.Models.Action", b =>
                {
                    b.HasOne("GamesResults.Models.ObjectType", "ObjectType")
                        .WithMany()
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ObjectType");
                });

            modelBuilder.Entity("GamesResults.Models.Log", b =>
                {
                    b.HasOne("GamesResults.Models.Action", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Object", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId");

                    b.HasOne("GamesResults.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Action");

                    b.Navigation("Object");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesResults.Models.LogDetail", b =>
                {
                    b.HasOne("GamesResults.Models.Log", "Log")
                        .WithMany()
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("GamesResults.Models.Object", b =>
                {
                    b.HasOne("GamesResults.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GamesResults.Models.User", "Deleter")
                        .WithMany()
                        .HasForeignKey("DeleterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GamesResults.Models.User", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GamesResults.Models.Object", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GamesResults.Models.ObjectType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("Deleter");

                    b.Navigation("Editor");

                    b.Navigation("Parent");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("GamesResults.Models.ObjectProperty", b =>
                {
                    b.HasOne("GamesResults.Models.ObjectType", "ObjectType")
                        .WithMany("Properties")
                        .HasForeignKey("ObjectTypeId");

                    b.Navigation("ObjectType");
                });

            modelBuilder.Entity("GamesResults.Models.ObjectType", b =>
                {
                    b.HasOne("GamesResults.Models.Container", "RootContainer")
                        .WithMany()
                        .HasForeignKey("RootContainerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("RootContainer");
                });

            modelBuilder.Entity("ObjectPropertiesEditRoles", b =>
                {
                    b.HasOne("GamesResults.Models.ObjectProperty", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UsersRoles", b =>
                {
                    b.HasOne("GamesResults.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.PlayerRating", b =>
                {
                    b.HasOne("GamesResults.Models.Object", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.PlayerRating", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Bowling.Player", "Player")
                        .WithOne("PlayerRating")
                        .HasForeignKey("GamesResults.Models.Bowling.PlayerRating", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.RatingHistory", b =>
                {
                    b.HasOne("GamesResults.Models.Object", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.RatingHistory", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Bowling.PlayerRating", "PlayerRating")
                        .WithMany("History")
                        .HasForeignKey("PlayerRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Bowling.Tournament", "Tournament")
                        .WithMany("History")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerRating");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Team", b =>
                {
                    b.HasOne("GamesResults.Models.Object", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.Team", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.TeamMember", b =>
                {
                    b.HasOne("GamesResults.Models.Object", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.TeamMember", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Bowling.Player", "Player")
                        .WithMany("TeamMembers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Bowling.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Tournament", b =>
                {
                    b.HasOne("GamesResults.Models.Bowling.City", "City")
                        .WithMany("Tournaments")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamesResults.Models.Object", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.Tournament", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Bowling.Oil", "Oil")
                        .WithMany("Tournaments")
                        .HasForeignKey("OilId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Oil");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.TournamentDocument", b =>
                {
                    b.HasOne("GamesResults.Models.Object", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.TournamentDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Bowling.Tournament", "Tournament")
                        .WithMany("Documents")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.TournamentResult", b =>
                {
                    b.HasOne("GamesResults.Models.Bowling.Bowling", "Bowling")
                        .WithMany("Results")
                        .HasForeignKey("BowlingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamesResults.Models.Object", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.TournamentResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Bowling.Player", "Player")
                        .WithMany("TournamentResults")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Bowling.Team", "Team")
                        .WithMany("TournamentResults")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamesResults.Models.Bowling.Tournament", "Tournament")
                        .WithMany("Results")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bowling");

                    b.Navigation("Player");

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("GamesResults.Models.Container", b =>
                {
                    b.HasOne("GamesResults.Models.Object", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Container", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesResults.Models.DictionaryItem", b =>
                {
                    b.HasOne("GamesResults.Models.DictionaryType", "DictionaryType")
                        .WithMany()
                        .HasForeignKey("DictionaryTypeId");

                    b.HasOne("GamesResults.Models.Object", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.DictionaryItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DictionaryType");
                });

            modelBuilder.Entity("GamesResults.Models.Component", b =>
                {
                    b.HasOne("GamesResults.Models.Container", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Component", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesResults.Models.Action", "LoadAction")
                        .WithMany()
                        .HasForeignKey("LoadActionId");

                    b.Navigation("LoadAction");
                });

            modelBuilder.Entity("GamesResults.Models.DictionaryType", b =>
                {
                    b.HasOne("GamesResults.Models.Container", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.DictionaryType", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesResults.Models.System", b =>
                {
                    b.HasOne("GamesResults.Models.Container", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.System", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Bowling", b =>
                {
                    b.HasOne("GamesResults.Models.DictionaryItem", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.Bowling", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.City", b =>
                {
                    b.HasOne("GamesResults.Models.Bowling.District", "District")
                        .WithMany("Cities")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamesResults.Models.DictionaryItem", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.City", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Discipline", b =>
                {
                    b.HasOne("GamesResults.Models.DictionaryItem", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.Discipline", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.District", b =>
                {
                    b.HasOne("GamesResults.Models.DictionaryItem", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.District", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Oil", b =>
                {
                    b.HasOne("GamesResults.Models.DictionaryItem", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.Oil", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Player", b =>
                {
                    b.HasOne("GamesResults.Models.Bowling.City", "City")
                        .WithMany("Players")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Players_City");

                    b.HasOne("GamesResults.Models.Bowling.District", "District")
                        .WithMany("Players")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamesResults.Models.DictionaryItem", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Bowling.Player", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("District");
                });

            modelBuilder.Entity("GamesResults.Models.Page", b =>
                {
                    b.HasOne("GamesResults.Models.Component", null)
                        .WithOne()
                        .HasForeignKey("GamesResults.Models.Page", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesResults.Models.ObjectType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.PlayerRating", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("TournamentResults");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Tournament", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("History");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Bowling", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.City", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.District", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Oil", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("GamesResults.Models.Bowling.Player", b =>
                {
                    b.Navigation("PlayerRating");

                    b.Navigation("TeamMembers");

                    b.Navigation("TournamentResults");
                });
#pragma warning restore 612, 618
        }
    }
}
